# TODO: Set up a dedicated domain name
baseURL = "https://mountain-view-yimby.gitlab.io/mv-yimby-hugo"
languageCode = "en-us"
# title = "Mountain View YIMBY"  # Set directly in layouts/partials/head.html.
theme = "timer-hugo"

[menu]  # Top menu bar.
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2  # Controls ordering.
  [[menu.nav]]
    name    = "Values"
    url     = "values"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

[params]  # Site Params
  home = "Home"
  # TODO: Downsize the logo or fix CSS (it's too big for the template).
  logo = "images/sb-yimby-logo.png"
  dateFormat = "January 6, 2006"
  # Meta data
  description = "Public site for Mountain View YIMBY."
  author = "MV YIMBY"
  googleAnalitycsID = "Your ID"  # TODO: Set up Google Analytics.

  [params.banner]  # Banner Section
    enable  = true
    bgImage = "images/mountain-view-osm.png"
    heading = "We are Mountain View YIMBY"
    description = "We are committed to a positive vision of housing for Mountain View."

    # CSS gets a bit messed up if these aren't all the same length.
    [[params.banner.flipText]]
      title = "AFFORDABLE"
    [[params.banner.flipText]]
      title = "ACCESSIBLE"
    [[params.banner.flipText]]
      title = "EQUITABLE"

  [params.about]  # Homepage About Section
    enable  = true
    title   = "About Us"
    content = "We are an offshoot of <a href=https://southbayyimby.wordpress.com/>South Bay YIMBY</a>."
    image   = "images/about/about.jpg"

  [params.cta]  # Call to Action
    enable  = true
    title   = "Ready to pitch in?"
    content = "Help make Mountain View an affordable place to live for everyone."
    btnText = "Get Involved"
    btnURL  = "/signup"

  [params.footer]

    # Icon font info: https://ionicons.com
    [[params.footer.socialIcon]]
      icon = "ion-social-facebook"
      url = "#"

    [[params.footer.socialIcon]]
      icon = "ion-social-twitter"
      url = "#"
