baseurl = "https://mvyimby.com/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
staticdir     = "static"
title = "Mountain View YIMBY"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
googleAnalytics = "UA-158028362-1"


[Params]
  subtitle = "A positive vision for housing in Mountain View"
  logo = "/mv-yimby-logo.png"
  favicon = "/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  author = "MV YIMBY Leads"
  twitter = "MVyimby"
  facebook = "mvyimby"
  # TODO: Set up Google Custom Search Engine.
  #  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

  custom_css = ["css/custom.css"]
  # custom_js = ["js/custom.js"]
  gtag_id = "AW-981091562"
  
  
[[Params.bigimg]]
  src = "img/IMG_4009-wide.jpg"
  desc = "Homes"

[[Params.bigimg]]
  src = "img/IMG_4213-wide.jpg"
  desc = "Homes and Trees"

[[Params.bigimg]]
  src = "img/IMG_7781-wide.jpg"
  desc = "Homes and Transit"

[Author]
  name = "MV YIMBY Leads"
  twitter = "MVyimby"
  facebook = "mvyimby"

# To allow Youtube Embeds, among other things
# see: https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032
[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
    name = "Posts"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Calendar"
    url = "page/calendar/"
    weight = 1

[[menu.main]]
    name = "Housing Element"
    url = "page/housingelement/"
    weight = 1

[[menu.main]]
    name = "Join"
    url = "page/join/"
    weight = 2
